name: CI

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Teste 
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          repository: therafs/rotten-potatoes
          auto_tag: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.8.0
        with:
          context: ./src
          push: true
          tags: therafs/rotten-potatoes:${{ env.GITHUB_ACTION	}}

          
        
          
